import { createRuntime } from '@oh-awesome-novel/runtime';
import { createReadTools, createRestrictedWriteTools } from '@oh-awesome-novel/tools';
import type {
  RuntimeEvent,
  RuntimeMessage,
  RuntimeModelAdapter,
  RuntimeModelRequest,
  RuntimeModelResponse,
  RuntimeModelStreamEvent,
  RuntimeToolCall,
} from '@oh-awesome-novel/runtime';
import type { ToolSet } from 'ai';

export type CheckpointLevel = 'level-1' | 'level-2' | 'level-3';

export interface NovelAgentCheckpointInput {
  workspaceRoot: string;
  request: string;
  level?: CheckpointLevel;
  tools?: ToolSet;
}

export function streamNovelAgentCheckpointTurn(
  input: NovelAgentCheckpointInput,
): AsyncIterable<RuntimeEvent> {
  const runtime = createRuntime({
    model: createCheckpointModelAdapter(input.level ?? inferCheckpointLevel(input.request)),
    tools: input.tools ?? createNovelAgentValidationTools(input.workspaceRoot),
    maxToolLoops: 4,
  });

  return runtime.streamTurn({
    messages: [
      {
        role: 'system',
        content:
          'You are running an oh-awesome-novel checkpoint validation turn.',
      },
      {
        role: 'user',
        content: input.request,
      },
    ],
  });
}

export function createNovelAgentValidationTools(workspaceRoot: string): ToolSet {
  return {
    ...createReadTools({ workspaceRoot }),
    ...createRestrictedWriteTools({ workspaceRoot }),
    'workspace.proposeWrite': createWorkspaceProposeWriteTool(),
  } as ToolSet;
}

function createWorkspaceProposeWriteTool(): ToolSet[string] {
  return {
    description:
      'Create a PendingAction preview for a workspace file write without writing to disk.',
    inputSchema: {
      type: 'object',
      properties: {
        path: { type: 'string' },
        content: { type: 'string' },
      },
      required: ['path', 'content'],
      additionalProperties: false,
    },
    async execute(args: unknown) {
      const path = getStringArg(args, 'path');
      const content = getStringArg(args, 'content');
      const pendingAction = {
        id: `pending-${Date.now().toString(36)}`,
        title: `Propose write to ${path}`,
        description:
          'Validation pending action generated by the checkpoint runner. It does not write files.',
        patches: [
          {
            type: 'validation.writeFile',
            path,
            content,
          },
        ],
        touchedFiles: [path],
        diff: [
          `--- a/${path}`,
          `+++ b/${path}`,
          '@@',
          ...content.split('\n').map((line) => `+${line}`),
        ].join('\n'),
        createdAt: new Date().toISOString(),
        status: 'pending' as const,
      };

      return {
        pendingActions: [pendingAction],
      };
    },
  } as ToolSet[string];
}

function createCheckpointModelAdapter(level: CheckpointLevel): RuntimeModelAdapter {
  let step = 0;

  return {
    async generate(request): Promise<RuntimeModelResponse> {
      let response: RuntimeModelResponse = {};

      for await (const event of this.stream?.(request) ?? []) {
        if (event.type === 'finish') {
          response = event.response;
        }
      }

      return response;
    },
    async *stream(request: RuntimeModelRequest): AsyncIterable<RuntimeModelStreamEvent> {
      const response = nextCheckpointResponse(level, step, request.messages);
      step += 1;

      for (const chunk of splitText(response.text)) {
        yield {
          type: 'text_delta',
          text: chunk,
        };
      }

      yield {
        type: 'finish',
        response: {
          message: {
            role: 'assistant',
            content: response.text,
          },
          toolCalls: response.toolCalls,
        },
      };
    },
  };
}

function nextCheckpointResponse(
  level: CheckpointLevel,
  step: number,
  messages: RuntimeMessage[],
): { text: string; toolCalls: RuntimeToolCall[] } {
  if (step > 0) {
    return {
      text: summarizeToolResults(level, messages),
      toolCalls: [],
    };
  }

  if (level === 'level-1') {
    return {
      text: 'Level 1: reading workflow and constitution so the UI can watch tool activity.',
      toolCalls: [
        { id: 'checkpoint-workflow', name: 'workflow.get', args: {} },
        { id: 'checkpoint-constitution', name: 'constitution.get', args: {} },
      ],
    };
  }

  if (level === 'level-2') {
    return {
      text: 'Level 2: reading heroine and state data through the runtime tool loop.',
      toolCalls: [
        { id: 'checkpoint-character', name: 'character.get', args: { id: 'heroine' } },
        {
          id: 'checkpoint-state',
          name: 'state.get',
          args: { file: 'characters.yaml', path: 'characters.heroine.hp' },
        },
      ],
    };
  }

  return {
    text: 'Level 3: creating a pending write preview without materializing changes.',
    toolCalls: [
      {
        id: 'checkpoint-pending-write',
        name: 'workspace.proposeWrite',
        args: {
          path: 'chapters/0001/checkpoint-preview.md',
          content: '闯卡验证：这里是一次待审批的写入预览。',
        },
      },
    ],
  };
}

function summarizeToolResults(level: CheckpointLevel, messages: RuntimeMessage[]): string {
  const toolMessages = messages.filter((message) => message.role === 'tool');
  const names = toolMessages.map((message) => message.name).filter(Boolean);

  if (level === 'level-3') {
    return `Level 3 complete: pending action is ready. Tools: ${names.join(', ')}.`;
  }

  return `Checkpoint complete. Tools: ${names.join(', ')}.`;
}

function inferCheckpointLevel(request: string): CheckpointLevel {
  const text = request.toLowerCase();

  if (text.includes('level 3') || text.includes('写入') || text.includes('pending')) {
    return 'level-3';
  }

  if (text.includes('level 2') || text.includes('character') || text.includes('state')) {
    return 'level-2';
  }

  return 'level-1';
}

function splitText(text: string): string[] {
  return text.match(/.{1,18}/g) ?? [text];
}

function getStringArg(args: unknown, name: string): string {
  if (
    typeof args !== 'object' ||
    args === null ||
    typeof (args as Record<string, unknown>)[name] !== 'string'
  ) {
    throw new Error(`Expected string argument "${name}".`);
  }

  return (args as Record<string, string>)[name];
}
