import { execFile } from 'node:child_process';
import { createHash } from 'node:crypto';
import { lstat, mkdtemp, realpath, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { isAbsolute, join, relative, sep } from 'node:path';
import { gitFileModesMatch } from './filesystem-modes';
import { promisify } from 'node:util';

const execFileAsync = promisify(execFile);

export interface RepositoryBaseline {
  repositoryId: string;
  branch: string;
  head: string;
}

export interface GitCommandError {
  code:
    | 'git_unavailable'
    | 'not_git_repository'
    | 'identity_missing'
    | 'head_missing'
    | 'remote_missing'
    | 'auth_failed'
    | 'conflict'
    | 'invalid_input'
    | 'stale_preview'
    | 'index_recovery_required'
    | 'git_failed';
  message: string;
  stderr?: string;
}

export interface GitFileStatus {
  path: string;
  originalPath?: string;
  indexStatus: string;
  worktreeStatus: string;
  raw: string;
}

export interface GitWorkspaceStatus {
  available: boolean;
  source: 'global';
  version?: string;
  repository: boolean;
  branch?: string;
  head?: string;
  status: 'clean' | 'dirty' | 'unknown';
  dirty: boolean | null;
  files: GitFileStatus[];
  error?: GitCommandError;
}

export interface GitCommitSummary {
  hash: string;
  shortHash: string;
  subject: string;
  authorName?: string;
  authorEmail?: string;
  authoredAt?: string;
}

export interface GitCommitDetail extends GitCommitSummary {
  body: string;
  files: Array<{
    path: string;
    originalPath?: string;
    status: string;
  }>;
  diff: string;
}

export type GitCommitResult =
  | { status: 'committed'; hash: string; message: string; warning?: GitCommandError }
  | { status: 'skipped'; reason: 'auto_commit_disabled'; message: string }
  | { status: 'failed'; message: string; error: GitCommandError };

export type GitSyncResult =
  | { status: 'synced'; fetch: string; pull: string; push: string }
  | { status: 'failed'; step: 'fetch' | 'pull' | 'push'; error: GitCommandError };

export interface PendingActionGitBaselineFile {
  path: string;
  exists: boolean;
  sha256?: string;
  mode?: number;
}

export interface PendingActionGitPreflight {
  branch: string;
  head: string;
  stagedFiles: string[];
  unrelatedStagedFiles: string[];
  dirtyBaselineFiles: string[];
}

export type PendingActionScopedCommitResult =
  | { status: 'committed'; commit: string; branch: string }
  | { status: 'staged-not-committed'; branch: string; errorCode: string }
  | { status: 'failed'; errorCode: string };

export interface PendingActionHeadCommit {
  commit: string;
  branch: string;
}

/** Trusted creation workflow only: never run when opening/importing a workspace. */
export async function initializeWorkspaceRepository(workspaceRoot: string): Promise<GitWorkspaceStatus> {
  try {
    await lstat(join(workspaceRoot, '.git'));
    throw gitResultError({ code: 'invalid_input', message: 'Workspace already has Git metadata.' });
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
  }

  const initialized = await runGit(workspaceRoot, ['init', '-b', 'main']);
  if (!initialized.ok) {
    return { ...await readGitStatus(workspaceRoot), error: initialized.error };
  }
  const identity = await runGit(workspaceRoot, ['var', 'GIT_AUTHOR_IDENT']);
  if (!identity.ok) return { ...await readGitStatus(workspaceRoot), error: identity.error };

  // Only files generated by initWorkspace belong to this initial baseline.
  // Do not use add-all: imported or concurrently created content is not approved.
  const stage = await runGit(workspaceRoot, [
    'add', '--', '.gitignore', '.oan/config.yaml', '.oan/workflow.yaml',
  ]);
  if (!stage.ok) return { ...await readGitStatus(workspaceRoot), error: stage.error };
  const committed = await runGit(workspaceRoot, [
    'commit', '--only', '-m', 'chore(novel): initialize workspace',
    '--', '.gitignore', '.oan/config.yaml', '.oan/workflow.yaml',
  ]);
  return {
    ...await readGitStatus(workspaceRoot),
    ...(!committed.ok ? { error: committed.error } : {}),
  };
}

export async function readGitStatus(workspaceRoot: string): Promise<GitWorkspaceStatus> {
  const version = await readGitVersion();
  if (!version.available) {
    return {
      available: false,
      source: 'global',
      repository: false,
      status: 'unknown',
      dirty: null,
      files: [],
      error: version.error,
    };
  }

  const root = await runGit(workspaceRoot, ['rev-parse', '--show-toplevel']);
  if (!root.ok) {
    return {
      available: true,
      source: 'global',
      version: version.version,
      repository: false,
      status: 'unknown',
      dirty: null,
      files: [],
      error: root.error,
    };
  }

  if (await realpath(root.stdout.trim()) !== await realpath(workspaceRoot)) {
    return {
      available: true, source: 'global', version: version.version, repository: false,
      status: 'unknown', dirty: null, files: [],
      error: {
        code: 'not_git_repository',
        message: 'The workspace needs its own Git repository; a parent repository cannot be used.',
      },
    };
  }

  const [branch, head, status] = await Promise.all([
    runGit(workspaceRoot, ['branch', '--show-current']),
    runGit(workspaceRoot, ['rev-parse', 'HEAD']),
    runGit(workspaceRoot, ['status', '--porcelain=v1', '-z', '--untracked-files=all']),
  ]);

  if (!status.ok) {
    return {
      available: true,
      source: 'global',
      version: version.version,
      repository: true,
      branch: branch.ok ? branch.stdout.trim() || undefined : undefined,
      head: head.ok ? head.stdout.trim() || undefined : undefined,
      status: 'unknown',
      dirty: null,
      files: [],
      error: status.error,
    };
  }

  // Existing/imported workspaces may lack our generated .gitignore. Public
  // status must never expose approval artifacts or disposable session paths.
  const files = parseStatusPorcelain(status.stdout).filter((file) =>
    !isInternalGitStatusPath(file.path)
    && (!file.originalPath || !isInternalGitStatusPath(file.originalPath)));
  const dirty = files.length > 0;
  const identity = await runGit(workspaceRoot, ['var', 'GIT_AUTHOR_IDENT']);

  return {
    available: true,
    source: 'global',
    version: version.version,
    repository: true,
    branch: branch.ok ? branch.stdout.trim() || undefined : undefined,
    head: head.ok ? head.stdout.trim() || undefined : undefined,
    status: dirty ? 'dirty' : 'clean',
    dirty,
    files,
    ...(!identity.ok ? { error: identity.error } : !head.ok ? {
      error: missingHeadError(),
    } : {}),
  };
}

export async function readRepositoryBaseline(
  workspaceRoot: string,
): Promise<RepositoryBaseline> {
  const [root, branch, head] = await Promise.all([
    runGit(workspaceRoot, ['rev-parse', '--show-toplevel']),
    runGit(workspaceRoot, ['branch', '--show-current']),
    runGit(workspaceRoot, ['rev-parse', 'HEAD']),
  ]);
  if (!root.ok) throw gitResultError(root.error);
  if (!branch.ok) throw gitResultError(branch.error);
  if (!head.ok) throw gitResultError(missingHeadError());

  const repositoryRoot = await realpath(root.stdout.trim());
  if (repositoryRoot !== await realpath(workspaceRoot)) {
    throw gitResultError({
      code: 'not_git_repository',
      message: 'The workspace needs its own Git repository; a parent repository cannot be used.',
    });
  }
  const branchName = branch.stdout.trim();
  return {
    repositoryId: createHash('sha256').update(repositoryRoot).digest('hex'),
    branch: branchName || `detached:${head.stdout.trim()}`,
    head: head.stdout.trim(),
  };
}

export async function assertRepositoryBaseline(
  workspaceRoot: string,
  expected: RepositoryBaseline,
): Promise<void> {
  const actual = await readRepositoryBaseline(workspaceRoot);
  if (
    actual.repositoryId !== expected.repositoryId
    || actual.branch !== expected.branch
    || actual.head !== expected.head
  ) {
    const error = new Error('Repository baseline is stale.');
    Object.assign(error, { code: 'STALE_REPOSITORY_BASELINE' });
    throw error;
  }
}

export async function gitDiff(workspaceRoot: string, files?: string[]): Promise<string> {
  const status = await readGitStatus(workspaceRoot);
  if (!status.repository || status.status === 'unknown') {
    throw gitResultError(status.error ?? { code: 'git_failed', message: 'Cannot read Git status.' });
  }
  const safeFiles = validateWorkspaceRelativePaths(workspaceRoot, files?.length ? files
    : status.files.flatMap((file) => file.originalPath ? [file.originalPath, file.path] : [file.path]), true);
  await assertGitFilePaths(workspaceRoot, safeFiles);
  if (safeFiles.length === 0) return '';

  // Preview exactly the worktree bytes an explicit commit will stage, including
  // untracked files, without touching the author's real index.
  const directory = await mkdtemp(join(tmpdir(), 'oan-git-preview-'));
  const env = { ...process.env, GIT_INDEX_FILE: join(directory, 'index') };
  try {
    const base = await runGit(workspaceRoot, ['read-tree', status.head ?? '--empty'], env);
    if (!base.ok) throw gitResultError(base.error);
    const stage = await runGit(workspaceRoot, ['update-index', '--add', '--remove', '--', ...safeFiles], env);
    if (!stage.ok) throw gitResultError(stage.error);
    const result = await runGit(workspaceRoot, [
      'diff', '--cached', '--no-ext-diff', '--no-textconv',
      ...(status.head ? [status.head] : []), '--', ...safeFiles,
    ], env);
    if (!result.ok) throw gitResultError(result.error);
    return result.stdout;
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
}

export async function gitStatusShort(workspaceRoot: string, files?: string[]): Promise<string> {
  const args = ['status', '--short'];
  const safeFiles = files?.length ? validateWorkspaceRelativePaths(workspaceRoot, files) : [];
  if (safeFiles.length) {
    args.push('--', ...safeFiles);
  }

  const result = await runGit(workspaceRoot, args);
  return result.ok ? result.stdout : '';
}

export async function listGitCommits(
  workspaceRoot: string,
  input: { maxCount?: number } = {},
): Promise<{ commits: GitCommitSummary[]; error?: GitCommandError }> {
  const maxCount = Math.min(Math.max(input.maxCount ?? 30, 1), 100);
  const result = await runGit(workspaceRoot, [
    'log',
    `--max-count=${maxCount}`,
    '--date=iso-strict',
    '--pretty=format:%H%x1f%h%x1f%an%x1f%ae%x1f%ad%x1f%s',
  ]);

  if (!result.ok) {
    return { commits: [], error: result.error };
  }

  return {
    commits: result.stdout
      .split('\n')
      .map((line) => line.trim())
      .filter(Boolean)
      .map(parseLogLine),
  };
}

export async function showGitCommit(
  workspaceRoot: string,
  hash: string,
): Promise<GitCommitDetail | { error: GitCommandError }> {
  if (!/^[0-9a-f]{7,40}$/iu.test(hash)) {
    return {
      error: {
        code: 'invalid_input',
        message: 'Commit hash is invalid.',
      },
    };
  }

  const [metadata, files, diff] = await Promise.all([
    runGit(workspaceRoot, [
      'show',
      '--quiet',
      '--date=iso-strict',
      '--pretty=format:%H%x1f%h%x1f%an%x1f%ae%x1f%ad%x1f%s%x1f%b',
      hash,
    ]),
    runGit(workspaceRoot, ['show', '--name-status', '-z', '--format=', hash]),
    runGit(workspaceRoot, ['show', '--format=', '--patch', hash]),
  ]);

  if (!metadata.ok) {
    return { error: metadata.error };
  }

  const summary = parseLogLine(metadata.stdout);
  return {
    ...summary,
    body: metadata.stdout.split('\x1f').slice(6).join('\x1f').trim(),
    files: files.ok ? parseNameStatus(files.stdout) : [],
    diff: diff.ok ? diff.stdout : '',
  };
}

/** Explicit user commits require the exact preview returned by prepareGitCommitPreview. */
export async function commitFiles(input: import('./git-reviewed-commit').ReviewedGitCommitInput): Promise<GitCommitResult> {
  const { commitReviewedGitFiles } = await import('./git-reviewed-commit');
  return commitReviewedGitFiles(input);
}

/** Internal adapter shared by the reviewed-commit module, never a frontend passthrough. */
export const reviewedGitHelpers = { runGit, validateWorkspaceRelativePaths, assertGitFilePaths, gitResultError };

/**
 * Revalidates the Git boundary used by ChangeMaterializer. The baseline check
 * is against the proposal HEAD, not the current worktree: this detects user
 * edits that already existed before the accepted candidate was materialized.
 */
export async function inspectPendingActionGitPreflight(input: {
  workspaceRoot: string;
  expected: RepositoryBaseline;
  files: readonly PendingActionGitBaselineFile[];
}): Promise<PendingActionGitPreflight> {
  await assertRepositoryBaseline(input.workspaceRoot, input.expected);
  const paths = validateWorkspaceRelativePaths(
    input.workspaceRoot,
    input.files.map((file) => file.path),
  );
  if (paths.length !== input.files.length) {
    throw Object.assign(new Error('PendingAction Git paths contain duplicates.'), {
      code: 'invalid_input',
    });
  }

  const staged = await runGit(input.workspaceRoot, [
    'diff',
    '--cached',
    '--name-only',
    '--no-renames',
    '-z',
  ]);
  if (!staged.ok) throw gitResultError(staged.error);
  const stagedFiles = parseNulPaths(staged.stdout);
  const acceptedPaths = new Set(paths);
  const unrelatedStagedFiles = stagedFiles.filter((file) => !acceptedPaths.has(file));

  const dirtyBaselineFiles: string[] = [];
  const fileMode = await runGit(input.workspaceRoot, ['config', '--default', 'true', '--type=bool', '--get', 'core.filemode']);
  if (!fileMode.ok) throw gitResultError(fileMode.error);
  const tracksExecutableMode = fileMode.stdout.trim() === 'true';
  for (const file of input.files) {
    const headEntry = await readHeadFile(input.workspaceRoot, input.expected.head, file.path);
    if (!file.exists) {
      if (headEntry !== undefined) dirtyBaselineFiles.push(file.path);
      continue;
    }
    if (
      headEntry === undefined
      || headEntry.sha256 !== file.sha256
      || file.mode === undefined
      || !gitFileModesMatch(file.mode, headEntry.mode, tracksExecutableMode)
    ) {
      dirtyBaselineFiles.push(file.path);
    }
  }

  return {
    branch: input.expected.branch,
    head: input.expected.head,
    stagedFiles,
    unrelatedStagedFiles,
    dirtyBaselineFiles,
  };
}

/**
 * Stages and commits only an already accepted action's paths. `onStaged` is
 * awaited after `git add` so the caller can durably record the recovery point.
 */
export async function commitPendingActionFiles(input: {
  workspaceRoot: string;
  files: readonly string[];
  message: string;
  onStaged?: () => Promise<void>;
}): Promise<PendingActionScopedCommitResult> {
  const files = validateWorkspaceRelativePaths(input.workspaceRoot, [...input.files]);
  if (files.length === 0) return { status: 'failed', errorCode: 'invalid_input' };

  const branch = await runGit(input.workspaceRoot, ['branch', '--show-current']);
  if (!branch.ok) return { status: 'failed', errorCode: branch.error.code };
  const branchName = branch.stdout.trim();
  if (!branchName) return { status: 'failed', errorCode: 'detached_head' };

  const stagedBefore = await runGit(input.workspaceRoot, [
    'diff',
    '--cached',
    '--name-only',
    '--no-renames',
    '-z',
  ]);
  if (!stagedBefore.ok) return { status: 'failed', errorCode: stagedBefore.error.code };
  const acceptedPaths = new Set(files);
  const unrelated = parseNulPaths(stagedBefore.stdout)
    .filter((file) => !acceptedPaths.has(file));
  if (unrelated.length > 0) {
    return { status: 'failed', errorCode: 'unrelated_staged_files' };
  }

  // An accepted path may already be staged with bytes that differ from the
  // approved final state. Always rebuild every accepted index entry from the
  // canonical files that ChangeMaterializer just revalidated.
  // `git add -A -- deleted-path` fails when that deletion is already staged,
  // because the path exists in neither the worktree nor the index. update-index
  // provides the equivalent exact-path refresh and is idempotent for staged
  // deletions while still replacing pre-existing staged create/update bytes.
  const add = await runGit(input.workspaceRoot, [
    'update-index',
    '--add',
    '--remove',
    '--',
    ...files,
  ]);
  if (!add.ok) return { status: 'failed', errorCode: add.error.code };
  const stagedAfter = await runGit(input.workspaceRoot, [
    'diff',
    '--cached',
    '--name-only',
    '--no-renames',
    '-z',
  ]);
  if (!stagedAfter.ok) return { status: 'failed', errorCode: stagedAfter.error.code };
  const stagedAfterFiles = parseNulPaths(stagedAfter.stdout);
  if (
    stagedAfterFiles.length !== files.length
    || stagedAfterFiles.some((file) => !acceptedPaths.has(file))
  ) {
    return { status: 'failed', errorCode: 'incomplete_staged_action' };
  }
  try {
    await input.onStaged?.();
  } catch (error) {
    return {
      status: 'staged-not-committed',
      branch: branchName,
      errorCode: safeErrorCode(error, 'after_git_add_failed'),
    };
  }

  const commit = await runGit(input.workspaceRoot, ['commit', '-m', input.message]);
  if (!commit.ok) {
    return {
      status: 'staged-not-committed',
      branch: branchName,
      errorCode: commit.error.code,
    };
  }
  const head = await runGit(input.workspaceRoot, ['rev-parse', 'HEAD']);
  if (!head.ok) {
    return {
      status: 'staged-not-committed',
      branch: branchName,
      errorCode: head.error.code,
    };
  }
  return { status: 'committed', commit: head.stdout.trim(), branch: branchName };
}

/** Finds the crash window where Git committed but the decision receipt did not. */
export async function readPendingActionCommitAtHead(input: {
  workspaceRoot: string;
  actionId: string;
  files: readonly string[];
  expectedRepository?: RepositoryBaseline;
  expectedCommit?: string;
}): Promise<PendingActionHeadCommit | undefined> {
  const files = validateWorkspaceRelativePaths(input.workspaceRoot, [...input.files]).sort();
  const [root, head, branch, body, changed, parents] = await Promise.all([
    runGit(input.workspaceRoot, ['rev-parse', '--show-toplevel']),
    runGit(input.workspaceRoot, ['rev-parse', 'HEAD']),
    runGit(input.workspaceRoot, ['branch', '--show-current']),
    runGit(input.workspaceRoot, ['show', '-s', '--format=%B', 'HEAD']),
    runGit(input.workspaceRoot, [
      'diff-tree',
      '--no-commit-id',
      '--name-only',
      '--no-renames',
      '-z',
      '-r',
      'HEAD',
    ]),
    runGit(input.workspaceRoot, ['rev-list', '--parents', '-n', '1', 'HEAD']),
  ]);
  if (!root.ok || !head.ok || !branch.ok || !body.ok || !changed.ok || !parents.ok) return undefined;
  const headCommit = head.stdout.trim();
  const branchName = branch.stdout.trim();
  if (input.expectedCommit !== undefined && headCommit !== input.expectedCommit) return undefined;
  if (input.expectedRepository !== undefined) {
    const repositoryRoot = await realpath(root.stdout.trim());
    const repositoryId = createHash('sha256').update(repositoryRoot).digest('hex');
    const ancestry = parents.stdout.trim().split(/\s+/u);
    if (
      repositoryId !== input.expectedRepository.repositoryId
      || branchName !== input.expectedRepository.branch
      || ancestry.length !== 2
      || ancestry[0] !== headCommit
      || ancestry[1] !== input.expectedRepository.head
    ) return undefined;
  }
  if (!body.stdout.split('\n').some((line) => line.trim() === `Pending-Action-Id: ${input.actionId}`)) {
    return undefined;
  }
  const committedFiles = parseNulPaths(changed.stdout).sort();
  if (
    committedFiles.length !== files.length
    || committedFiles.some((file, index) => file !== files[index])
  ) {
    return undefined;
  }
  if (!branchName) return undefined;
  return { commit: headCommit, branch: branchName };
}

export async function syncGit(workspaceRoot: string): Promise<GitSyncResult> {
  const fetch = await runGit(workspaceRoot, ['fetch']);
  if (!fetch.ok) {
    return { status: 'failed', step: 'fetch', error: fetch.error };
  }

  const pull = await runGit(workspaceRoot, ['pull', '--ff-only']);
  if (!pull.ok) {
    return { status: 'failed', step: 'pull', error: pull.error };
  }

  const push = await runGit(workspaceRoot, ['push']);
  if (!push.ok) {
    return { status: 'failed', step: 'push', error: push.error };
  }

  return {
    status: 'synced',
    fetch: fetch.stdout,
    pull: pull.stdout,
    push: push.stdout,
  };
}

export function createPendingActionCommitMessage(input: {
  pendingActionId: string;
  title: string;
}): string {
  const shortId = input.pendingActionId.replace(/^pa_/, '').slice(0, 8);
  return [
    `chore(novel): apply pending action ${shortId}`,
    '',
    input.title.trim(),
    '',
    `Pending-Action-Id: ${input.pendingActionId}`,
  ].join('\n');
}

async function readHeadFile(
  workspaceRoot: string,
  head: string,
  path: string,
): Promise<{ sha256: string; mode: number } | undefined> {
  const tree = await runGit(workspaceRoot, ['ls-tree', '-z', head, '--', path]);
  if (!tree.ok) throw gitResultError(tree.error);
  const records = tree.stdout.split('\0').filter((record) => record.length > 0);
  if (records.length === 0) return undefined;
  if (records.length !== 1) {
    throw Object.assign(new Error(`Git tree returned multiple entries for ${path}.`), {
      code: 'git_failed',
    });
  }
  const match = /^(100644|100755)\s+blob\s+([0-9a-f]{40,64})\t([\s\S]+)$/u.exec(records[0]!);
  if (!match || match[3] !== path) {
    throw Object.assign(new Error(`Git tree entry is invalid for ${path}.`), {
      code: 'git_failed',
    });
  }
  const blob = await runGit(workspaceRoot, ['cat-file', 'blob', match[2]!]);
  if (!blob.ok) throw gitResultError(blob.error);
  return {
    sha256: createHash('sha256').update(blob.stdout, 'utf8').digest('hex'),
    mode: Number.parseInt(match[1]!, 8) & 0o777,
  };
}

async function readGitVersion(): Promise<
  | { available: true; version: string }
  | { available: false; error: GitCommandError }
> {
  try {
    const { stdout } = await execFileAsync('git', ['--version']);
    return { available: true, version: stdout.trim() };
  } catch (error) {
    return {
      available: false,
      error: toGitCommandError(error),
    };
  }
}

async function runGit(
  workspaceRoot: string,
  args: string[],
  env?: NodeJS.ProcessEnv,
): Promise<
  | { ok: true; stdout: string; stderr: string }
  | { ok: false; error: GitCommandError }
> {
  try {
    const { stdout, stderr } = await execFileAsync('git', ['--no-optional-locks', '--literal-pathspecs', '-C', workspaceRoot, ...args], {
      maxBuffer: 20 * 1024 * 1024,
      ...(env ? { env } : {}),
    });
    return { ok: true, stdout, stderr };
  } catch (error) {
    return {
      ok: false,
      error: toGitCommandError(error),
    };
  }
}

function parseStatusPorcelain(stdout: string): GitFileStatus[] {
  const records = parseNulPaths(stdout);
  const files: GitFileStatus[] = [];
  for (let index = 0; index < records.length; index += 1) {
    const record = records[index]!;
    if (record.length < 4 || record[2] !== ' ') throw gitOutputError();
    const indexStatus = record[0]!;
    const worktreeStatus = record[1]!;
    const path = record.slice(3);
    const originalPath = /[RC]/u.test(indexStatus + worktreeStatus)
      ? records[++index] : undefined;
    if (/[RC]/u.test(indexStatus + worktreeStatus) && !originalPath) throw gitOutputError();
    files.push({
      path, indexStatus, worktreeStatus,
      ...(originalPath ? { originalPath } : {}),
      raw: `${indexStatus}${worktreeStatus} ${originalPath ? `${JSON.stringify(originalPath)} -> ` : ''}${JSON.stringify(path)}`,
    });
  }
  return files;
}

function isInternalGitStatusPath(path: string): boolean {
  return /^(?:\.git|\.workspace|\.oan\/(?:sessions|indexes))(?:\/|$)/u.test(path);
}

function parseNulPaths(stdout: string): string[] {
  if (stdout.length === 0) return [];
  const fields = stdout.split('\0');
  if (fields.at(-1) !== '') {
    throw Object.assign(new Error('Git path output was not NUL terminated.'), {
      code: 'git_failed',
    });
  }
  fields.pop();
  return fields;
}

function parseLogLine(line: string): GitCommitSummary {
  const [hash = '', shortHash = '', authorName, authorEmail, authoredAt, subject = ''] =
    line.split('\x1f');

  return {
    hash,
    shortHash,
    subject,
    authorName,
    authorEmail,
    authoredAt,
  };
}

function parseNameStatus(stdout: string): GitCommitDetail['files'] {
  const records = parseNulPaths(stdout);
  const files: GitCommitDetail['files'] = [];
  for (let index = 0; index < records.length; index += 1) {
    const status = records[index]!;
    const firstPath = records[++index];
    const renamed = /^[RC]/u.test(status);
    const path = renamed ? records[++index] : firstPath;
    if (!/^[A-Z][0-9]*$/u.test(status) || !firstPath || !path) throw gitOutputError();
    files.push({ status, path, ...(renamed ? { originalPath: firstPath } : {}) });
  }
  return files;
}

function validateWorkspaceRelativePaths(workspaceRoot: string, files: string[], allowWorkspaceMetadata = false): string[] {
  const uniqueFiles = [...new Set(files)];

  for (const file of uniqueFiles) {
    if (!file || isAbsolute(file) || /[\u0000-\u001f\u007f\\]/u.test(file)) {
      throw gitResultError({ code: 'invalid_input', message: `Unsupported workspace path: ${JSON.stringify(file)}` });
    }

    const parts = file.split('/');
    const metadataPath = allowWorkspaceMetadata && (
      file === '.gitignore'
      || /^\.oan\/(?:config\.yaml|workflow\.yaml|AGENTS\.md|CODEX\.md)$/u.test(file)
      || /^\.oan\/(?:constitution|writing-profiles|skills|prompts)\//u.test(file)
    );
    if (parts.some((part, index) => !part || (part.startsWith('.') && !(metadataPath && index === 0)))) {
      throw gitResultError({ code: 'invalid_input', message: `Invalid workspace relative path: ${JSON.stringify(file)}` });
    }

    const relativePath = relative(workspaceRoot, `${workspaceRoot}${sep}${file}`);
    if (
      relativePath === '..' ||
      relativePath.startsWith(`..${sep}`) ||
      isAbsolute(relativePath)
    ) {
      throw new Error(`Path is outside workspace: ${file}`);
    }
  }

  return uniqueFiles;
}

async function assertGitFilePaths(workspaceRoot: string, files: string[]): Promise<void> {
  for (const file of files) {
    const parts = file.split('/');
    for (let index = 1; index <= parts.length; index += 1) {
      try {
        const entry = await lstat(join(workspaceRoot, ...parts.slice(0, index)));
        if (entry.isSymbolicLink() || (index === parts.length ? !entry.isFile() : !entry.isDirectory())) {
          throw gitResultError({ code: 'invalid_input', message: `Git target must be a regular file: ${JSON.stringify(file)}` });
        }
      } catch (error) {
        if ((error as NodeJS.ErrnoException).code === 'ENOENT') break;
        throw error;
      }
    }
  }
}

function gitOutputError(): Error {
  return gitResultError({ code: 'git_failed', message: 'Git returned malformed NUL-delimited paths.' });
}

function missingHeadError(): GitCommandError {
  return {
    code: 'head_missing',
    message: 'This workspace has no initial Git commit. Configure a Git identity and create the initial commit in your external editor before using Copilot.',
  };
}

function failedCommit(message: string, error: GitCommandError): GitCommitResult {
  return {
    status: 'failed',
    message,
    error,
  };
}

function safeErrorCode(error: unknown, fallback: string): string {
  const code = typeof error === 'object' && error !== null && 'code' in error
    ? (error as { code?: unknown }).code
    : undefined;
  return typeof code === 'string' && /^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/u.test(code)
    ? code
    : fallback;
}

function gitResultError(error: GitCommandError): Error {
  const result = new Error(error.message);
  Object.assign(result, { code: error.code, stderr: error.stderr });
  return result;
}

function toGitCommandError(error: unknown): GitCommandError {
  const stderr = readProcessStderr(error);
  const message = stderr || (error instanceof Error ? error.message : String(error));
  const normalized = message.toLowerCase();

  if (normalized.includes('not a git repository')) {
    return { code: 'not_git_repository', message: 'Workspace is not a Git repository.', stderr };
  }

  if (normalized.includes('unable to auto-detect email address')
    || normalized.includes('please tell me who you are')
    || normalized.includes('empty ident name')
    || normalized.includes('empty ident email')) {
    return { code: 'identity_missing', message: 'Git user identity is not configured. Set user.name and user.email for this repository in your external editor, then create the initial commit if needed.', stderr };
  }

  if (normalized.includes('no configured push destination') || normalized.includes('does not appear to be a git repository')) {
    return { code: 'remote_missing', message: 'Git remote is not configured.', stderr };
  }

  if (normalized.includes('authentication failed') || normalized.includes('permission denied')) {
    return { code: 'auth_failed', message: 'Git authentication failed.', stderr };
  }

  if (normalized.includes('would be overwritten') || normalized.includes('conflict')) {
    return { code: 'conflict', message: 'Git operation cannot continue because of conflicts.', stderr };
  }

  if (
    normalized.includes('enoent') ||
    normalized.includes('spawn git') ||
    normalized.includes('command not found')
  ) {
    return { code: 'git_unavailable', message: 'Global git command is not available.', stderr };
  }

  return { code: 'git_failed', message: message || 'Git command failed.', stderr };
}

function readProcessStderr(error: unknown): string | undefined {
  if (
    typeof error === 'object' &&
    error !== null &&
    'stderr' in error &&
    typeof (error as { stderr?: unknown }).stderr === 'string'
  ) {
    const stderr = (error as { stderr: string }).stderr.trim();
    return stderr || undefined;
  }

  return undefined;
}
